version: '3'
services:
  db:
    image: mysql
    volumes:
      - ./scripts/stats.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  gopher:
    build: .
    command: bundle exec gopher2000/bin/gopher2000 gopherpedia.rb
    volumes:
      - .:/app
    ports:
      - "7070:7070"
    links:
      - db
    depends_on:
      - db
    tty: true
    stdin_open: true
  web:
    image: muffinista/gophper-proxy
    links:
      - db
      - gopher
    depends_on:
      - db
      - gopher
    environment:
      docker: "true"
      production: "false"
      ALLOW_ALL_PORTS: "false"
      RESTRICT_TO_MATCH: "/gopherpedia.com/"
      START_REQUEST: "gopherpedia.com:70"
      APP_NAME: "Gopherpedia"
    volumes:
      - .:/var/www/html:cached
      - ./logs:/var/www/logs:cached
    ports:
      - 8080:80
