version: '3'
services:
  db:
    image: library/mariadb:5.5.56
    volumes:
      - ./scripts/stats.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: on-failure
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    networks:
      - internal_network
  gopher:
    build: .
    command: bin/wait-for-it db:3306 -- bundle exec gopher2000 gopherpedia.rb
    restart: on-failure
    environment:
      GOPHER_PORT: 70
      GOPHERPEDIA_DB_URI: 'mysql2://root:@db/gopherpedia'
    ports:
      #- "70:7070"
      - "70:70"
    depends_on:
      - db
    tty: true
    stdin_open: true
    # volumes:
    #   - .:/app
    #   - bundle_cache:/usr/local/bundle
    networks:
      - internal_network
      - external_network
  web:
    image: muffinista/gopher-proxy
    restart: on-failure
    depends_on:
      - db
      - gopher
    environment:
      docker: "true"
      production: "true"
      ALLOW_ALL_PORTS: "false"
      RESTRICT_TO_MATCH: "/gopherpedia.com/"
      START_REQUEST: "gopherpedia.com"
      APP_NAME: "Gopherpedia"
      GOPHER_TITLE: "Gopherpedia"
      GOPHER_ABOUT_URL: "/about"
      GOPHER_DESCRIPTION: "Gopherpedia, the gopher interface to Wikipedia."
    ports:
      - "8080:80"
    networks:
      - internal_network
      - external_network
networks:
  external_network:
  internal_network:
    internal: true
volumes:
  bundle_cache:
