#FROM php:7.2.2-fpm
FROM php:5.6.35-apache

WORKDIR /var/www/html

COPY ./ /var/www/html/

RUN apt-get update && apt-get install -y git sqlite3 zlib1g-dev libssl-dev --no-install-recommends \
    && docker-php-ext-install pdo zip mysqli \
    && a2enmod rewrite


#RUN pecl install swoole
#RUN docker-php-ext-enable swoole
