#!/bin/bash

PIDFILE="/tmp/gopher-ping.pid"
export LC_ALL="en_US.UTF-8"

if [ -f $PIDFILE ] && ps -p `cat $PIDFILE` > /dev/null;
then
   # Do something knowing the pid exists, i.e. the process with $PID is running
   echo "RUNNING" > /dev/null
else
    echo "NOT RUNNING"
    /bin/bash -c "echo $$ > $PIDFILE; rvmsudo /home/colin/.rvm/gems/ruby-2.1.2/bin/gopher2000 ./gopherpedia.rb >> /tmp/startup.log"
fi



